sudo: false


jobs:
  include:
    - stage: frontend
      language: node_js
      node_js:
        - "8"
      cache:
        - yarn
      script: cd web && yarn install && yarn build
    - stage: tests
      services:
        - docker
      script:
        - cp docker/test.env ./.env
        - docker-compose up -d --build
        - docker-compose exec api python manage.py makemigrations
        - docker-compose exec api python manage.py migrate
        - docker-compose exec api python manage.py test
    - stage: deploy
      services:
        - docker
      script:
        - bash .travis/deploy.sh

stages:
  - name: tests
    if: type IN (push, pull_request) AND branch IN (master, develop)
  - name: frontend
    if: type IN (push, pull_request) AND branch IN (master, develop)
  - name: deploy
    if: type IN (push) AND branch IN (master)
