version: '3'

services:
  db:
    image: postgres
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: bash ./docker/wait-for-it.sh db:5432 -- python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ../.env
    volumes:
      - ../server/pcoippoolmanager:/server/pcoippoolmanager
      - ../server/pools:/server/pools
    ports:
      - "8000:8000"
    depends_on:
      - db
